apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hxd6cj4z8-nodejs
  janus-idp.io/tekton: hxd6cj4z8-nodejs
  backstage.io/kubernetes-id: hxd6cj4z8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hxd6cj4z8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
