apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hxd6cj4z8-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hxd6cj4z8-nodejs 
  name: hxd6cj4z8-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hxd6cj4z8-nodejs 
